[package]
name = "sched_deadline"
version = "0.2.0"
authors = ["Stephan Creutz <stephan.cr@gmx.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
flagset = "0.4"
libc = "0.2.68"

[dev-dependencies]
caps = "0.5"
scopeguard = "1.1.0"
